version: '3.5'

services:
    backend:
        image: backend-docker
        ports: 
          - 8000:8000
        environment:
          - REDIS=redis
          - FRONT_URL=http:/localhost/
          - DB_PASSWORD=sekretpw123
          - DB_USERNAME=postgres
          - DB_HOST=postgres
    frontend:
        image: frontend-docker
        ports: 
          - 5000:5000
        environment:
          - API_URL=http://localhost/api/
    redis: 
        image: redis:6.0.9-alpine
        ports:
          - 6379:6379
    postgres:
        image: postgres
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=sekretpw123
    proxy:
        image: nginx
        volumes:
          - ./nginx.conf:/etc/nginx/nginx.conf
        ports:
          - 80:80
        depends_on: 
          - frontend
          - backend