version: '3'

services:
  backend:
    image: backend-docker
    ports:
      - 8000:8000
    environment:
      - API_URL=http://localhost:5000
  frontend:
    image: frontend-docker
    ports: 
      - 5000:5000
    environment:
      - FRONT_URL=http://localhost:8000    