version: '3'

services:
    backend:
        image: backend-docker
        ports: 
          - 8000:8000
        environment:
          - REDIS=redis
          - API_URL=http://localhost:5000
          - DB_PASSWORD=sekretpw123
          - DB_USERNAME=postgres
          - DB_HOST=postgres
    frontend:
      image: frontend-docker
      ports: 
        - 5000:5000
      environment:
        - FRONT_URL=http://localhost:8000    
    redis: 
        image: redis:6.0.9-alpine
        ports:
          - 6379:6379
    postgres:
        image: postgres
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=sekretpw123
        container_name: postgres